
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers/finalizers
  verbs:
  - update
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers/status
  verbs:
  - get
  - patch
  - update
