# permissions for end users to view scheduledscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledscaler-viewer-role
rules:
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers/status
  verbs:
  - get
