# permissions for end users to edit scheduledscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledscaler-editor-role
rules:
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaler.andikahmadr.io
  resources:
  - scheduledscalers/status
  verbs:
  - get
